sudo: required

services:
    - docker

before_install:
    - docker build -t pradhanamit77/docker-react -f Dockerfile.dev .

script:
    -docker run pradhanamit77/docker-react npm run test -- --coverage